language: objective-c
osx_image: xcode8.3
env:
  - DESTINATION="OS=10.3,name=iPhone 6s" SCHEME="XLPagerTabStrip" SDK=iphonesimulator10.3
before_install:
- brew update
#- brew outdated carthage || brew upgrade carthage
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
#- carthage update --platform iOS
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- xcodebuild clean build -project XLPagerTabStrip.xcodeproj -scheme "$SCHEME" -sdk "$SDK"
#- xcodebuild test -project XLPagerTabStrip.xcodeproj -scheme "$SCHEME" -sdk "$SDK"
- xcodebuild -project XLPagerTabStrip.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION"
  -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
